'use client'

import { createContext, useContext, useEffect, useState } from 'react'

type Language = 'en' | 'vi'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export const translations = {
  en: {
    dashboard: 'Dashboard',
    documents: 'Documents',
    chat: 'AI Chat',
    analytics: 'Analytics',
    profile: 'Profile',
    admin: 'Admin',
    settings: 'Settings',
    billing: 'Billing',
    help: 'Help',
    language: 'Language',
    smartLearning: 'Smart Learning',
    upgrade: 'Upgrade to Pro',
    unlockFeatures: 'Unlock unlimited AI chats and advanced analytics',
    upgradeNow: 'Upgrade Now',
    searchGlobal: 'Search documents, chats...',
    myAccount: 'My Account',
    signedIn: 'Signed in',
    student: 'Student',
    logOut: 'Log out',
    welcome: 'Welcome back',
    learningQuestion: 'Ready to continue your learning journey?',
    askAi: 'Ask AI',
    totalDocuments: 'Total Documents',
    aiChats: 'AI Chats',
    subjects: 'Subjects',
    workspaces: 'Workspaces',
    recentUploads: 'Recent Uploads',
    realData: 'real data',
    soon: 'soon',
    latest: 'latest',
    recentDocuments: 'Recent Documents',
    viewAll: 'View All',
    noDocuments: 'No documents yet',
    noRecentDocuments: 'No documents yet. Upload your first study file from the Documents page.',
    uncategorized: 'Uncategorized',
    pages: 'pages',
    aiRecommendations: 'AI Recommendations',
    reviewFlashcards: 'Review Flashcards',
    reviewFlashcardsDesc: 'Flashcard generation will use your uploaded documents.',
    startReview: 'Start Review',
    quizAvailable: 'Quiz Available',
    quizAvailableDesc: 'Quizzes will appear after AI processing is connected.',
    takeQuiz: 'Take Quiz',
    studySession: 'Study Session',
    studySessionDesc: 'Upload documents to start building your study history.',
    continue: 'Continue',
    quickActions: 'Quick Actions',
    upload: 'Upload',
    flashcards: 'Flashcards',
    favorites: 'Favorites',
    recentActivity: 'Recent Activity',
    activityPlaceholder: 'Activity will appear after uploads, chats, quizzes, and flashcards are connected.',
    documentsSubtitle: 'Upload real study files. The backend stores them in Supabase Storage when configured.',
    dropFilesHere: 'Drop your files here',
    dragDropFiles: 'Drag & drop files here',
    supportedFiles: 'PDF, Word, and PowerPoint files are supported',
    uploading: 'Uploading',
    uploadComplete: 'Upload Complete!',
    uploadCompleteShort: 'Upload complete',
    filesUploaded: 'files uploaded',
    searchDocuments: 'Search documents...',
    loadingDocuments: 'Loading documents...',
    noDocumentsSubtext: 'Upload your first file to save it in storage and SQL Server.',
    unknownSize: 'Unknown size',
    view: 'View',
    download: 'Download',
    editDetails: 'Edit Details',
    share: 'Share',
    addTag: 'Add Tag',
    delete: 'Delete',
    editDocument: 'Edit Document',
    title: 'Title',
    description: 'Description',
    visibility: 'Visibility',
    private: 'Private',
    public: 'Public',
    shared: 'Shared',
    cancel: 'Cancel',
    saveChanges: 'Save Changes',
    shareLinkCopied: 'Share link copied',
    documentUpdated: 'Document updated',
    couldNotLoadDocuments: 'Could not load documents',
    couldNotUpdateFavorite: 'Could not update favorite',
    couldNotDeleteDocument: 'Could not delete document',
    couldNotCreateShareLink: 'Could not create share link',
    couldNotUpdateDocument: 'Could not update document',
    newChat: 'New Chat',
    noMessagesYet: 'No messages yet',
    recent: 'Recent',
    aiIntro: "Hello! I'm your AI study assistant. I can help you understand your documents, create flashcards, generate quizzes, and answer questions about your study materials. What would you like to learn today?",
    suggestedPrompts: 'Suggested prompts:',
    promptSummarize: 'Summarize my Machine Learning notes',
    promptFlashcards: 'Create flashcards for Chemistry Ch.5',
    promptQuiz: 'Generate a quiz on Linear Algebra',
    promptConcepts: 'Explain key concepts from my notes',
    documentContext: 'Document context',
    generalAiChat: 'General AI chat',
    chatPlaceholder: 'Ask anything about your documents...',
    aiDisclaimer: 'AI Study Hub can make mistakes. Consider checking important information.',
    loginFirst: 'Please log in first.',
    newStudyChat: 'New Study Chat',
    createChatFailed: 'Could not create chat session',
    aiRequestFailed: 'AI request failed',
    managePreferences: 'Manage your account preferences',
    profileInformation: 'Profile Information',
    firstName: 'First Name',
    lastName: 'Last Name',
    email: 'Email',
    bio: 'Bio',
    noEmail: 'No email',
    noBioYet: 'No bio yet.',
    bioTemplate: 'student at',
    yourUniversity: 'your university',
    notifications: 'Notifications',
    notificationPreferences: 'Notification Preferences',
    emailNotifications: 'Email Notifications',
    emailNotificationsDesc: 'Receive updates about your documents and AI chats',
    pushNotifications: 'Push Notifications',
    pushNotificationsDesc: 'Get notified about new features and recommendations',
    studyReminders: 'Study Reminders',
    studyRemindersDesc: 'Daily reminders to review your flashcards',
    weeklySummary: 'Weekly Summary',
    weeklySummaryDesc: 'Receive a weekly summary of your learning progress',
    appearance: 'Appearance',
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    system: 'System',
    security: 'Security',
    securitySettings: 'Security Settings',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    enterCurrentPassword: 'Enter current password',
    enterNewPassword: 'Enter new password',
    confirmNewPasswordPlaceholder: 'Confirm new password',
    updatePassword: 'Update Password',
    billingSubscription: 'Billing & Subscription',
    helpSupport: 'Help & Support',
    comingSoon: 'This section is coming soon. Contact support at support@aistudyhub.com for assistance.',
    smartLearningPlatform: 'Smart Learning Platform',
    login: 'Login',
    register: 'Register',
    fullName: 'Full Name',
    emailAddress: 'Email Address',
    invalidEmailFormat: 'Please enter a valid email address, for example name@example.com.',
    password: 'Password',
    forgotPassword: 'Forgot password?',
    forgotPasswordHelp: 'Enter your email and we will send a secure link to create a new password.',
    backToSignIn: 'Back to sign in',
    pleaseEnterEmail: 'Please enter your email address.',
    pleaseEnterLogin: 'Please enter email and password.',
    pleaseEnterRegister: 'Please enter your name, email, and password.',
    resetEmailSent: 'If that email exists, a password reset link has been sent.',
    couldNotSendReset: 'Could not send reset email',
    enterPassword: 'Enter your password',
    pleaseWait: 'Please wait...',
    sendResetLink: 'Send Reset Link',
    signIn: 'Sign In',
    createAccount: 'Create Account',
    orContinueWith: 'or continue with',
    googleNotConfigured: 'Google login is not configured. Add NEXT_PUBLIC_GOOGLE_CLIENT_ID in frontend/.env.local and GOOGLE_CLIENT_ID in backend/.env.',
    googleNoToken: 'Google did not return a login token. Please try again.',
    googleLoadFailed: 'Could not load Google login. Please check your connection and try again.',
    termsPrefix: 'By continuing, you agree to our',
    termsOfService: 'Terms of Service',
    privacyPolicy: 'Privacy Policy',
    and: 'and',
  },
  vi: {
    dashboard: 'Bảng điều khiển',
    documents: 'Tài liệu',
    chat: 'Trò chuyện AI',
    analytics: 'Phân tích',
    profile: 'Hồ sơ',
    admin: 'Quản trị',
    settings: 'Cài đặt',
    billing: 'Thanh toán',
    help: 'Trợ giúp',
    language: 'Ngôn ngữ',
    smartLearning: 'Học thông minh',
    upgrade: 'Nâng cấp Pro',
    unlockFeatures: 'Mở khóa trò chuyện AI không giới hạn và phân tích nâng cao',
    upgradeNow: 'Nâng cấp ngay',
    searchGlobal: 'Tìm tài liệu, đoạn chat...',
    myAccount: 'Tài khoản của tôi',
    signedIn: 'Đã đăng nhập',
    student: 'Sinh viên',
    logOut: 'Đăng xuất',
    welcome: 'Chào mừng trở lại',
    learningQuestion: 'Sẵn sàng tiếp tục hành trình học tập chưa?',
    askAi: 'Hỏi AI',
    totalDocuments: 'Tổng tài liệu',
    aiChats: 'Chat AI',
    subjects: 'Môn học',
    workspaces: 'Workspaces',
    recentUploads: 'Tải lên gần đây',
    realData: 'dữ liệu thật',
    soon: 'sắp có',
    latest: 'mới nhất',
    recentDocuments: 'Tài liệu gần đây',
    viewAll: 'Xem tất cả',
    noDocuments: 'Chưa có tài liệu',
    noRecentDocuments: 'Chưa có tài liệu. Hãy tải file học tập đầu tiên ở trang Tài liệu.',
    uncategorized: 'Chưa phân loại',
    pages: 'trang',
    aiRecommendations: 'Gợi ý từ AI',
    reviewFlashcards: 'Ôn flashcard',
    reviewFlashcardsDesc: 'Flashcard sẽ được tạo từ tài liệu bạn tải lên.',
    startReview: 'Bắt đầu ôn',
    quizAvailable: 'Có bài quiz',
    quizAvailableDesc: 'Quiz sẽ xuất hiện sau khi AI xử lý tài liệu.',
    takeQuiz: 'Làm quiz',
    studySession: 'Phiên học',
    studySessionDesc: 'Tải tài liệu lên để bắt đầu xây dựng lịch sử học tập.',
    continue: 'Tiếp tục',
    quickActions: 'Thao tác nhanh',
    upload: 'Tải lên',
    flashcards: 'Flashcard',
    favorites: 'Yêu thích',
    recentActivity: 'Hoạt động gần đây',
    activityPlaceholder: 'Hoạt động sẽ xuất hiện sau khi upload, chat, quiz và flashcard được kết nối.',
    documentsSubtitle: 'Tải file học tập thật. Backend sẽ lưu vào Supabase Storage khi đã cấu hình.',
    dropFilesHere: 'Thả file vào đây',
    dragDropFiles: 'Kéo thả file vào đây',
    supportedFiles: 'Hỗ trợ PDF, Word và PowerPoint',
    uploading: 'Đang tải lên',
    uploadComplete: 'Tải lên hoàn tất!',
    uploadCompleteShort: 'Tải lên hoàn tất',
    filesUploaded: 'file đã tải lên',
    searchDocuments: 'Tìm kiếm tài liệu...',
    loadingDocuments: 'Đang tải tài liệu...',
    noDocumentsSubtext: 'Tải file đầu tiên để lưu vào storage và SQL Server.',
    unknownSize: 'Không rõ dung lượng',
    view: 'Xem',
    download: 'Tải xuống',
    editDetails: 'Sửa chi tiết',
    share: 'Chia sẻ',
    addTag: 'Thêm thẻ',
    delete: 'Xóa',
    editDocument: 'Sửa tài liệu',
    title: 'Tiêu đề',
    description: 'Mô tả',
    visibility: 'Quyền hiển thị',
    private: 'Riêng tư',
    public: 'Công khai',
    shared: 'Đã chia sẻ',
    cancel: 'Hủy',
    saveChanges: 'Lưu thay đổi',
    shareLinkCopied: 'Đã sao chép link chia sẻ',
    documentUpdated: 'Đã cập nhật tài liệu',
    couldNotLoadDocuments: 'Không thể tải tài liệu',
    couldNotUpdateFavorite: 'Không thể cập nhật yêu thích',
    couldNotDeleteDocument: 'Không thể xóa tài liệu',
    couldNotCreateShareLink: 'Không thể tạo link chia sẻ',
    couldNotUpdateDocument: 'Không thể cập nhật tài liệu',
    newChat: 'Chat mới',
    noMessagesYet: 'Chưa có tin nhắn',
    recent: 'Gần đây',
    aiIntro: 'Xin chào! Tôi là trợ lý học tập AI của bạn. Tôi có thể giúp bạn hiểu tài liệu, tạo flashcard, tạo quiz và trả lời câu hỏi về nội dung học tập. Hôm nay bạn muốn học gì?',
    suggestedPrompts: 'Gợi ý câu hỏi:',
    promptSummarize: 'Tóm tắt ghi chú Machine Learning của tôi',
    promptFlashcards: 'Tạo flashcard cho Hóa học chương 5',
    promptQuiz: 'Tạo quiz về Đại số tuyến tính',
    promptConcepts: 'Giải thích các khái niệm chính trong ghi chú',
    documentContext: 'Ngữ cảnh tài liệu',
    generalAiChat: 'Chat AI chung',
    chatPlaceholder: 'Hỏi bất cứ điều gì về tài liệu của bạn...',
    aiDisclaimer: 'AI Study Hub có thể mắc lỗi. Hãy kiểm tra lại thông tin quan trọng.',
    loginFirst: 'Vui lòng đăng nhập trước.',
    newStudyChat: 'Chat học tập mới',
    createChatFailed: 'Không thể tạo phiên chat',
    aiRequestFailed: 'Yêu cầu AI thất bại',
    managePreferences: 'Quản lý tùy chọn tài khoản của bạn',
    profileInformation: 'Thông tin hồ sơ',
    firstName: 'Tên',
    lastName: 'Họ và tên đệm',
    email: 'Email',
    bio: 'Giới thiệu',
    noEmail: 'Chưa có email',
    noBioYet: 'Chưa có giới thiệu.',
    bioTemplate: 'học tại',
    yourUniversity: 'trường của bạn',
    notifications: 'Thông báo',
    notificationPreferences: 'Tùy chọn thông báo',
    emailNotifications: 'Thông báo email',
    emailNotificationsDesc: 'Nhận cập nhật về tài liệu và chat AI',
    pushNotifications: 'Thông báo đẩy',
    pushNotificationsDesc: 'Nhận thông báo về tính năng mới và gợi ý',
    studyReminders: 'Nhắc học',
    studyRemindersDesc: 'Nhắc hằng ngày để ôn flashcard',
    weeklySummary: 'Tổng kết tuần',
    weeklySummaryDesc: 'Nhận tổng kết hằng tuần về tiến độ học tập',
    appearance: 'Giao diện',
    theme: 'Chủ đề',
    light: 'Sáng',
    dark: 'Tối',
    system: 'Theo hệ thống',
    security: 'Bảo mật',
    securitySettings: 'Cài đặt bảo mật',
    currentPassword: 'Mật khẩu hiện tại',
    newPassword: 'Mật khẩu mới',
    confirmNewPassword: 'Xác nhận mật khẩu mới',
    enterCurrentPassword: 'Nhập mật khẩu hiện tại',
    enterNewPassword: 'Nhập mật khẩu mới',
    confirmNewPasswordPlaceholder: 'Xác nhận mật khẩu mới',
    updatePassword: 'Cập nhật mật khẩu',
    billingSubscription: 'Thanh toán & gói dịch vụ',
    helpSupport: 'Trợ giúp & hỗ trợ',
    comingSoon: 'Mục này sẽ sớm có. Liên hệ support@aistudyhub.com để được hỗ trợ.',
    smartLearningPlatform: 'Nền tảng học tập thông minh',
    login: 'Đăng nhập',
    register: 'Đăng ký',
    fullName: 'Họ và tên',
    emailAddress: 'Địa chỉ email',
    invalidEmailFormat: 'Vui lòng nhập đúng định dạng email, ví dụ name@example.com.',
    password: 'Mật khẩu',
    forgotPassword: 'Quên mật khẩu?',
    forgotPasswordHelp: 'Nhập email để nhận link bảo mật tạo mật khẩu mới.',
    backToSignIn: 'Quay lại đăng nhập',
    pleaseEnterEmail: 'Vui lòng nhập địa chỉ email.',
    pleaseEnterLogin: 'Vui lòng nhập email và mật khẩu.',
    pleaseEnterRegister: 'Vui lòng nhập họ tên, email và mật khẩu.',
    resetEmailSent: 'Nếu email tồn tại, link đặt lại mật khẩu đã được gửi.',
    couldNotSendReset: 'Không thể gửi email đặt lại mật khẩu',
    enterPassword: 'Nhập mật khẩu',
    pleaseWait: 'Vui lòng chờ...',
    sendResetLink: 'Gửi link đặt lại',
    signIn: 'Đăng nhập',
    createAccount: 'Tạo tài khoản',
    orContinueWith: 'hoặc tiếp tục với',
    googleNotConfigured: 'Google login chưa được cấu hình. Thêm NEXT_PUBLIC_GOOGLE_CLIENT_ID trong frontend/.env.local và GOOGLE_CLIENT_ID trong backend/.env.',
    googleNoToken: 'Google không trả về token đăng nhập. Vui lòng thử lại.',
    googleLoadFailed: 'Không thể tải Google login. Hãy kiểm tra kết nối và thử lại.',
    termsPrefix: 'Khi tiếp tục, bạn đồng ý với',
    termsOfService: 'Điều khoản dịch vụ',
    privacyPolicy: 'Chính sách quyền riêng tư',
    and: 'và',
  }
} as const

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en')

  useEffect(() => {
    const saved = localStorage.getItem('language') as Language | null
    if (saved === 'vi' || saved === 'en') {
      setLanguageState(saved)
      document.documentElement.lang = saved
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('language', lang)
    document.documentElement.lang = lang
  }

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider')
  }
  return context
}
